apiVersion: v1
kind: Pod
metadata:
  labels:
    pod-reaper: disable
  name: pod-reaper
spec:
  # don't restart the reaper, if the restart policy is "Always" (the default value) kubernetes will
  # reschedule the pod after it has completed.
  restartPolicy: Never
  containers:
  - image: target/pod-reaper:2.0.0
    name: pod-reaper
    env:
      - name: NAMESPACE
        value: default
      - name: SCHEDULE
        value: "@every 30s"
      - name: RUN_DURATION
        value: 5m
      - name: EXCLUDE_LABEL_KEY
        value: pod-reaper
      - name: EXCLUDE_LABEL_VALUES
        value: disable,off
      - name: CHAOS_CHANCE
        value: "0.5"
